cors:
  originPatterns: http://localhost:5050,http://localhost:5500,https://estudodosjovens.com.br,https://agenda-de-contatos-six-lac.vercel.app
spring:
  server:
    port: ${PORT:8080}
  application:
    name: contact
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
loggin:
  level: DEBUG